;;; projectile-cache-tests.el --- Tests for Projectile cache config -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)

(ert-deftest projectile-cache-settings-use-one-hour-transient-cache ()
  (should (eq projectile-enable-caching t))
  (should (= projectile-files-cache-expire 3600)))

(ert-deftest projectile-cache-find-file-without-prefix-keeps-cache ()
  (let (events seen-prefix)
    (cl-letf (((symbol-function 'projectile-invalidate-cache)
               (lambda (&rest _) (push 'invalidate events)))
              ((symbol-function 'helm-projectile-find-file)
               (lambda ()
                 (interactive)
                 (setq seen-prefix current-prefix-arg)
                 (push 'search events))))
      (let ((current-prefix-arg nil))
        (call-interactively #'my/helm-projectile-find-file)))
    (should (equal (nreverse events) '(search)))
    (should-not seen-prefix)))

(ert-deftest projectile-cache-find-file-with-prefix-invalidates-first ()
  (let (events seen-prefix)
    (cl-letf (((symbol-function 'projectile-invalidate-cache)
               (lambda (prompt)
                 (push (list 'invalidate prompt) events)))
              ((symbol-function 'helm-projectile-find-file)
               (lambda ()
                 (interactive)
                 (setq seen-prefix current-prefix-arg)
                 (push 'search events))))
      (let ((current-prefix-arg '(4)))
        (call-interactively #'my/helm-projectile-find-file)))
    (should (equal (nreverse events) '((invalidate nil) search)))
    (should-not seen-prefix)))

(ert-deftest projectile-cache-binds-project-shortcuts ()
  (let (leader-binding super-bindings)
    (cl-letf (((symbol-function 'spacemacs/set-leader-keys)
               (lambda (key command)
                 (setq leader-binding (list key command))))
              ((symbol-function 'global-set-key)
               (lambda (key command)
                 (push (list key command) super-bindings))))
      (my/projectile-cache-bind-keys))
    (should (equal leader-binding '("pf" my/helm-projectile-find-file)))
    (should (equal (nreverse super-bindings)
                   (list (list (kbd "s-p")
                               'helm-projectile-switch-project)
                         (list (kbd "s-f")
                               'my/helm-projectile-find-file)
                         (list (kbd "s-s")
                               'spacemacs/helm-project-smart-do-search))))))

(ert-deftest projectile-cache-installs-global-bindings-on-module-load ()
  (should (eq (global-key-binding (kbd "s-p"))
              'helm-projectile-switch-project))
  (should (eq (global-key-binding (kbd "s-f"))
              'my/helm-projectile-find-file))
  (should (eq (global-key-binding (kbd "s-s"))
              'spacemacs/helm-project-smart-do-search)))

(ert-deftest projectile-cache-switch-project-prefers-existing-buffer ()
  (let (switched-buffer)
    (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
               (lambda () '(existing-buffer)))
              ((symbol-function 'switch-to-buffer)
               (lambda (buffer &rest _)
                 (setq switched-buffer buffer)))
              ((symbol-function 'projectile-acquire-root)
               (lambda () (ert-fail "Should not inspect files"))))
      (my/projectile-switch-to-last-buffer-or-file))
    (should (eq switched-buffer 'existing-buffer))))

(ert-deftest projectile-cache-switch-project-prefers-root-documents-in-order ()
  (dolist (case '((("README.md" "AGENTS.md" "CLAUDE.md") "README.md")
                  (("AGENTS.md" "CLAUDE.md") "AGENTS.md")
                  (("CLAUDE.md") "CLAUDE.md")))
    (let ((existing (car case))
          (expected (cadr case))
          opened-file)
      (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
                 (lambda () nil))
                ((symbol-function 'projectile-acquire-root)
                 (lambda () "/tmp/project/"))
                ((symbol-function 'file-exists-p)
                 (lambda (file)
                   (member (file-name-nondirectory file) existing)))
                ((symbol-function 'projectile-project-files)
                 (lambda (&rest _)
                   (ert-fail "Should prefer the root document")))
                ((symbol-function 'find-file)
                 (lambda (file) (setq opened-file file))))
        (my/projectile-switch-to-last-buffer-or-file))
      (should (equal opened-file
                     (expand-file-name expected "/tmp/project/"))))))

(ert-deftest projectile-cache-switch-project-uses-first-indexed-file ()
  (let (opened-file)
    (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
               (lambda () nil))
              ((symbol-function 'projectile-acquire-root)
               (lambda () "/tmp/project/"))
              ((symbol-function 'file-exists-p) (lambda (&rest _) nil))
              ((symbol-function 'projectile-project-files)
               (lambda (root)
                 (should (equal root "/tmp/project/"))
                 '("src/first.el" "src/second.el")))
              ((symbol-function 'find-file)
               (lambda (file) (setq opened-file file))))
      (my/projectile-switch-to-last-buffer-or-file))
    (should (equal opened-file "/tmp/project/src/first.el"))))

(ert-deftest projectile-cache-switch-project-errors-when-project-has-no-files ()
  (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
             (lambda () nil))
            ((symbol-function 'projectile-acquire-root)
             (lambda () "/tmp/empty/"))
            ((symbol-function 'file-exists-p) (lambda (&rest _) nil))
            ((symbol-function 'projectile-project-files) (lambda (&rest _) nil)))
    (should-error (my/projectile-switch-to-last-buffer-or-file)
                  :type 'user-error)))

(ert-deftest projectile-cache-installs-project-switch-action ()
  (should (eq projectile-switch-project-action
              'my/projectile-switch-to-last-buffer-or-file)))

;;; projectile-cache-tests.el ends here
