;;; projectile-tests.el --- Tests for local Projectile config -*- lexical-binding: t -*-

(require 'ert)
(require 'cl-lib)
(require 'eieio)

(defclass projectile-config-test-helm-source ()
  ((candidates :initarg :candidates))
  "Minimal Helm-like source used to test EIEIO compatibility.")

(defmacro projectile-config-with-helm-source (source &rest body)
  "Evaluate BODY with Helm's project SOURCE globally bound to SOURCE."
  (declare (indent 1) (debug t))
  `(let ((was-bound (boundp 'helm-source-projectile-projects))
         (old-source (and (boundp 'helm-source-projectile-projects)
                          (symbol-value 'helm-source-projectile-projects))))
     (unwind-protect
         (progn
           (set 'helm-source-projectile-projects ,source)
           ,@body)
       (if was-bound
           (set 'helm-source-projectile-projects old-source)
         (makunbound 'helm-source-projectile-projects)))))

(ert-deftest projectile-config-settings-use-one-hour-transient-cache ()
  (should (eq projectile-enable-caching t))
  (should (= projectile-files-cache-expire 3600)))

(ert-deftest projectile-config-find-file-without-prefix-keeps-cache ()
  (let (events seen-prefix)
    (cl-letf (((symbol-function 'projectile-invalidate-cache)
               (lambda (&rest _) (push 'invalidate events)))
              ((symbol-function 'helm-projectile-find-file)
               (lambda ()
                 (interactive)
                 (setq seen-prefix current-prefix-arg)
                 (push 'search events))))
      (let ((current-prefix-arg nil))
        (call-interactively #'my/helm-projectile-find-file)))
    (should (equal (nreverse events) '(search)))
    (should-not seen-prefix)))

(ert-deftest projectile-config-find-file-with-prefix-invalidates-first ()
  (let (events seen-prefix)
    (cl-letf (((symbol-function 'projectile-invalidate-cache)
               (lambda (prompt)
                 (push (list 'invalidate prompt) events)))
              ((symbol-function 'helm-projectile-find-file)
               (lambda ()
                 (interactive)
                 (setq seen-prefix current-prefix-arg)
                 (push 'search events))))
      (let ((current-prefix-arg '(4)))
        (call-interactively #'my/helm-projectile-find-file)))
    (should (equal (nreverse events) '((invalidate nil) search)))
    (should-not seen-prefix)))

(ert-deftest projectile-config-binds-project-shortcuts ()
  (let (leader-bindings super-bindings)
    (cl-letf (((symbol-function 'spacemacs/set-leader-keys)
               (lambda (key command)
                 (push (list key command) leader-bindings)))
              ((symbol-function 'global-set-key)
               (lambda (key command)
                 (push (list key command) super-bindings))))
      (my/projectile-bind-keys))
    (should (equal (nreverse leader-bindings)
                   '(("pf" my/helm-projectile-find-file)
                     ("fyy" my/copy-file-path))))
    (should (equal (nreverse super-bindings)
                   (list (list (kbd "s-p")
                               'helm-projectile-switch-project)
                         (list (kbd "s-f")
                               'my/helm-projectile-find-file)
                         (list (kbd "s-s")
                               'spacemacs/helm-project-smart-do-search)
                         (list (kbd "s-g")
                               'magit-status))))))

(ert-deftest projectile-config-copy-file-path-relative-to-project ()
  (let (copied shown)
    (cl-letf (((symbol-function 'spacemacs--file-path)
               (lambda () "/tmp/project/src/example.el"))
              ((symbol-function 'projectile-project-root)
               (lambda (directory)
                 (should (equal directory "/tmp/project/src/"))
                 "/tmp/project/"))
              ((symbol-function 'kill-new) (lambda (text) (setq copied text)))
              ((symbol-function 'message) (lambda (format &rest args)
                                            (setq shown (apply #'format format args)))))
      (my/copy-file-path nil))
    (should (equal copied "src/example.el"))
    (should (equal shown copied))))

(ert-deftest projectile-config-copy-file-path-prefix-keeps-full-path ()
  (let (copied)
    (cl-letf (((symbol-function 'spacemacs--file-path)
               (lambda () "/tmp/project/src/example.el"))
              ((symbol-function 'projectile-project-root)
               (lambda (&rest _)
                 (ert-fail "A prefix should skip project lookup")))
              ((symbol-function 'kill-new) (lambda (text) (setq copied text)))
              ((symbol-function 'message) #'ignore))
      (my/copy-file-path '(4)))
    (should (equal copied "/tmp/project/src/example.el"))))

(ert-deftest projectile-config-copy-file-path-outside-project-keeps-full-path ()
  (let (copied)
    (cl-letf (((symbol-function 'spacemacs--file-path)
               (lambda () "/tmp/notes/example.txt"))
              ((symbol-function 'projectile-project-root) (lambda (&rest _) nil))
              ((symbol-function 'kill-new) (lambda (text) (setq copied text)))
              ((symbol-function 'message) #'ignore))
      (my/copy-file-path nil))
    (should (equal copied "/tmp/notes/example.txt"))))

(ert-deftest projectile-config-installs-global-bindings-on-module-load ()
  (should (eq (global-key-binding (kbd "s-p"))
              'helm-projectile-switch-project))
  (should (eq (global-key-binding (kbd "s-f"))
              'my/helm-projectile-find-file))
  (should (eq (global-key-binding (kbd "s-s"))
              'spacemacs/helm-project-smart-do-search))
  (should (eq (global-key-binding (kbd "s-g"))
              'magit-status)))

(ert-deftest projectile-config-switch-project-prefers-existing-buffer ()
  (let ((existing-buffer (generate-new-buffer " *project-existing*"))
        switched-buffer)
    (unwind-protect
        (progn
          (with-current-buffer existing-buffer
            (setq buffer-file-name "/tmp/project/existing.el"))
          (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
                     (lambda () (list existing-buffer)))
                    ((symbol-function 'switch-to-buffer)
                     (lambda (buffer &rest _)
                       (setq switched-buffer buffer)))
                    ((symbol-function 'projectile-acquire-root)
                     (lambda () (ert-fail "Should not inspect files"))))
            (my/projectile-switch-to-last-buffer-or-file))
          (should (eq switched-buffer existing-buffer)))
      (kill-buffer existing-buffer))))

(ert-deftest projectile-config-switch-project-skips-non-text-buffers ()
  (let ((agent-buffer (generate-new-buffer " *project-agent*"))
        (special-buffer (generate-new-buffer " *project-special*"))
        (text-buffer (generate-new-buffer " *project-text*"))
        switched-buffer)
    (unwind-protect
        (progn
          (with-current-buffer special-buffer
            (setq buffer-file-name "/tmp/project/image.png")
            (special-mode))
          (with-current-buffer text-buffer
            (setq buffer-file-name "/tmp/project/notes.md"))
          (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
                     (lambda ()
                       (list agent-buffer special-buffer text-buffer)))
                    ((symbol-function 'switch-to-buffer)
                     (lambda (buffer &rest _)
                       (setq switched-buffer buffer)))
                    ((symbol-function 'projectile-acquire-root)
                     (lambda () (ert-fail "Should not inspect files"))))
            (my/projectile-switch-to-last-buffer-or-file))
          (should (eq switched-buffer text-buffer)))
      (kill-buffer agent-buffer)
      (kill-buffer special-buffer)
      (kill-buffer text-buffer))))

(ert-deftest projectile-config-switch-project-prefers-root-documents-in-order ()
  (dolist (case '((("README.md" "AGENTS.md" "CLAUDE.md") "README.md")
                  (("AGENTS.md" "CLAUDE.md") "AGENTS.md")
                  (("CLAUDE.md") "CLAUDE.md")))
    (let ((existing (car case))
          (expected (cadr case))
          opened-file)
      (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
                 (lambda () nil))
                ((symbol-function 'projectile-acquire-root)
                 (lambda () "/tmp/project/"))
                ((symbol-function 'file-exists-p)
                 (lambda (file)
                   (member (file-name-nondirectory file) existing)))
                ((symbol-function 'projectile-project-files)
                 (lambda (&rest _)
                   (ert-fail "Should prefer the root document")))
                ((symbol-function 'find-file)
                 (lambda (file) (setq opened-file file))))
        (my/projectile-switch-to-last-buffer-or-file))
      (should (equal opened-file
                     (expand-file-name expected "/tmp/project/"))))))

(ert-deftest projectile-config-switch-project-uses-first-indexed-file ()
  (let (opened-file)
    (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
               (lambda () nil))
              ((symbol-function 'projectile-acquire-root)
               (lambda () "/tmp/project/"))
              ((symbol-function 'file-exists-p) (lambda (&rest _) nil))
              ((symbol-function 'projectile-project-files)
               (lambda (root)
                 (should (equal root "/tmp/project/"))
                 '("src/first.el" "src/second.el")))
              ((symbol-function 'find-file)
               (lambda (file) (setq opened-file file))))
      (my/projectile-switch-to-last-buffer-or-file))
    (should (equal opened-file "/tmp/project/src/first.el"))))

(ert-deftest projectile-config-switch-project-errors-when-project-has-no-files ()
  (cl-letf (((symbol-function 'projectile-project-buffers-non-visible)
             (lambda () nil))
            ((symbol-function 'projectile-acquire-root)
             (lambda () "/tmp/empty/"))
            ((symbol-function 'file-exists-p) (lambda (&rest _) nil))
            ((symbol-function 'projectile-project-files) (lambda (&rest _) nil)))
    (should-error (my/projectile-switch-to-last-buffer-or-file)
                  :type 'user-error)))

(ert-deftest projectile-config-installs-project-switch-action ()
  (should (eq projectile-switch-project-action
              'my/projectile-switch-to-last-buffer-or-file)))

(ert-deftest projectile-config-promotes-selected-project-to-front ()
  (let ((merge-count 0))
    (cl-letf (((symbol-value 'projectile-known-projects)
               '("/tmp/first/" "/tmp/selected/" "/tmp/last/"))
              ((symbol-function 'projectile-known-projects)
               (lambda () (symbol-value 'projectile-known-projects)))
              ((symbol-function 'projectile-merge-known-projects)
               (lambda () (cl-incf merge-count))))
      (my/projectile-promote-selected-project "/tmp/selected")
      (should (equal (symbol-value 'projectile-known-projects)
                     '("/tmp/selected/" "/tmp/first/" "/tmp/last/"))))
    (should (= merge-count 1))))

(ert-deftest projectile-config-mru-promotion-skips-no-ops ()
  (let ((merge-count 0))
    (cl-letf (((symbol-value 'projectile-known-projects)
               '("/tmp/first/" "/tmp/last/"))
              ((symbol-function 'projectile-known-projects)
               (lambda () (symbol-value 'projectile-known-projects)))
              ((symbol-function 'projectile-merge-known-projects)
               (lambda () (cl-incf merge-count))))
      (my/projectile-promote-selected-project "/tmp/first/")
      (my/projectile-promote-selected-project "/tmp/unknown/")
      (should (equal (symbol-value 'projectile-known-projects)
                     '("/tmp/first/" "/tmp/last/"))))
    (should (= merge-count 0))))

(ert-deftest projectile-config-installs-mru-advice-once ()
  (my/projectile-install-mru-tracking)
  (my/projectile-install-mru-tracking)
  (should (advice-member-p #'my/projectile-promote-selected-project
                           #'projectile-switch-project-by-name)))

(ert-deftest projectile-config-switch-candidates-use-project-buffer ()
  (let ((project-buffer (generate-new-buffer " *project-candidates-origin*"))
        seen-buffer)
    (unwind-protect
        (let ((helm-current-buffer project-buffer))
          (cl-letf (((symbol-function 'projectile-relevant-known-projects)
                     (lambda ()
                       (setq seen-buffer (current-buffer))
                       '("/tmp/recent/" "/tmp/older/"))))
            (with-temp-buffer
              (should
               (equal (my/helm-projectile-switch-project-candidates)
                      '("/tmp/recent/" "/tmp/older/")))))
          (should (eq seen-buffer project-buffer)))
      (kill-buffer project-buffer))))

(ert-deftest projectile-config-installs-relevant-helm-candidates ()
  (let ((source '((candidates . ignore))))
    (projectile-config-with-helm-source source
      (my/helm-projectile-install-relevant-project-candidates)
      (should (eq (alist-get 'candidates source)
                  #'my/helm-projectile-switch-project-candidates)))))

(ert-deftest projectile-config-installs-relevant-eieio-helm-candidates ()
  (let ((source (projectile-config-test-helm-source :candidates #'ignore)))
    (projectile-config-with-helm-source source
      (my/helm-projectile-install-relevant-project-candidates)
      (should (eq (slot-value source 'candidates)
                  #'my/helm-projectile-switch-project-candidates)))))

(ert-deftest projectile-config-does-not-prebind-helm-projectile-source ()
  (should-not (boundp 'helm-source-projectile-projects)))

;;; projectile-tests.el ends here
